<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0;net48</TargetFrameworks>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseSystemDrawing>true</UseSystemDrawing>
    <TargetExt>.rhp</TargetExt>
    <NoWarn>NU1701</NoWarn>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0</Version>
    <Title>Rhino Modifiers</Title>
    <Company>Dan Kenerson, Moritz Rietschel, Chuck Driesler, Joshua Foxley</Company>
    <Description>Adds Blender-like modifiers to Rhino</Description>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="wrench.png" />

    <PackageReference Include="RhinoCommon" Version="8.0.23304.9001" ExcludeAssets="runtime" />
    <PackageReference Include="Grasshopper" Version="8.0.23304.9001" ExcludeAssets="runtime" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
  </ItemGroup>
</Project>
