using System;
using System.Collections.Generic;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Parameters;
using Grasshopper.Kernel.Special;
using RhinoModifiers.Models;
using Rhino.Geometry;

namespace RhinoModifiers.Runtime
{
    /// <summary>
    /// Represents a stack queued for eventual processing.
    /// </summary>
    internal readonly record struct QueuedStack(uint DocumentSerial, Guid ObjectId, string Key);

    /// <summary>
    /// Holds geometry generated by a stack intended for lightweight viewport preview.
    /// </summary>
    public readonly record struct PreviewStack(Guid SourceObjectId, IReadOnlyList<GeometryBase> Geometry);

    /// <summary>
    /// Describes the inputs, outputs, and scene geometry requirements for a Grasshopper definition.
    /// </summary>
    internal sealed record DefinitionContract(
        ModifierInputDescriptor? SceneInput,
        IReadOnlyList<ModifierInputDescriptor> Inputs,
        IReadOnlyList<ModifierOutputDescriptor> Outputs,
        IReadOnlyList<ModifierOutputDescriptor> GeometryOutputs);

    /// <summary>
    /// Provides metadata about a specific input parameter required by a modifier.
    /// </summary>
    internal sealed record ModifierInputDescriptor(
        Guid ObjectId,
        string Id,
        string Label,
        string Description,
        ModifierIoKind Kind,
        string DefaultSerializedValue,
        bool HasDefaultValue,
        bool UsesSceneGeometryWhenBlank,
        bool IsOptional,
        double? Minimum,
        double? Maximum,
        int DecimalPlaces)
    {
        public IReadOnlyList<string> ValueListItems { get; init; } = Array.Empty<string>();

        public bool IsFilePath { get; init; }
    }

    /// <summary>
    /// Provides metadata about a specific output parameter yielded by a modifier.
    /// </summary>
    internal sealed record ModifierOutputDescriptor(
        Guid ObjectId,
        string Id,
        string Label,
        string Description,
        ModifierIoKind Kind);

    /// <summary>
    /// Binds an input descriptor to its live Grasshopper parameter or UI control equivalent.
    /// </summary>
    internal sealed class RuntimeInputBinding
    {
        public RuntimeInputBinding(ModifierInputDescriptor descriptor, IGH_Param param)
        {
            Descriptor = descriptor;
            Param = param;
        }

        public RuntimeInputBinding(ModifierInputDescriptor descriptor, GH_NumberSlider slider)
        {
            Descriptor = descriptor;
            Slider = slider;
        }

        public RuntimeInputBinding(ModifierInputDescriptor descriptor, GH_ValueList valueList)
        {
            Descriptor = descriptor;
            ValueList = valueList;
        }

        public ModifierInputDescriptor Descriptor { get; }

        public IGH_Param? Param { get; }

        public GH_NumberSlider? Slider { get; }

        public GH_ValueList? ValueList { get; }

        public void Expire()
        {
            Param?.ExpireSolution(false);
            Slider?.ExpireSolution(false);
            ValueList?.ExpireSolution(false);
        }
    }

    /// <summary>
    /// Binds an output descriptor to its live Grasshopper parameter.
    /// </summary>
    internal sealed class RuntimeOutputBinding
    {
        public RuntimeOutputBinding(ModifierOutputDescriptor descriptor, IGH_Param param)
        {
            Descriptor = descriptor;
            Param = param;
        }

        public ModifierOutputDescriptor Descriptor { get; }

        public IGH_Param Param { get; }

        public void Expire()
        {
            Param.ExpireSolution(false);
        }
    }

    /// <summary>
    /// Contains the resolved output values from a single modifier step.
    /// </summary>
    internal readonly record struct StepOutputValue(string Id, string DisplayValue, IReadOnlyList<object> Values);

    /// <summary>
    /// Bundles all necessary evaluation and structural details to render a step in the UI panel.
    /// </summary>
    internal sealed record PanelStepContext(
        int Index,
        ModifierStepSpec Step,
        string DisplayName,
        DefinitionContract? Contract,
        string ContractError);

    /// <summary>
    /// Represents the UI state and validation status of linked module connections.
    /// </summary>
    internal readonly record struct LinkPresentationState(
        bool HasLink,
        bool IsBroken,
        string SourceStepLabel,
        string SourceOutputLabel,
        string StatusMessage)
    {
        public static LinkPresentationState None => new(false, false, string.Empty, string.Empty, string.Empty);
    }

    /// <summary>
    /// Captures the comprehensive result of evaluating a single modifier step, including geometry, raw outputs, and errors.
    /// </summary>
    internal readonly record struct StepEvaluationResult(
        bool Success,
        bool HasGeometryOutput,
        List<GeometryBase> OutputGeometry,
        List<StepOutputValue> PublishedOutputs,
        string ErrorMessage,
        int RawGeometryOutputItemCount,
        List<string> SkippedGeometryOutputTypes)
    {
        public static StepEvaluationResult Successful(
            bool hasGeometryOutput,
            List<GeometryBase> outputGeometry,
            List<StepOutputValue> publishedOutputs,
            int rawGeometryOutputItemCount,
            List<string> skippedGeometryOutputTypes)
        {
            return new StepEvaluationResult(
                true,
                hasGeometryOutput,
                outputGeometry,
                publishedOutputs,
                string.Empty,
                rawGeometryOutputItemCount,
                skippedGeometryOutputTypes);
        }

        public static StepEvaluationResult Fail(string message)
        {
            return new StepEvaluationResult(
                false,
                false,
                new List<GeometryBase>(),
                new List<StepOutputValue>(),
                message,
                0,
                new List<string>());
        }
    }
}
