using System.Drawing;
using System.Linq;
using Rhino;
using Rhino.Display;
using Rhino.DocObjects;
using Rhino.Geometry;

namespace RhinoModifiers.UI;

/// <summary>
/// A display conduit responsible for previewing the geometry generated by active modifier stacks.
/// </summary>
internal sealed class StackPreviewConduit : DisplayConduit
{
    private static readonly Color PreviewColor = Color.OrangeRed;
    private readonly RhinoModifiers.Runtime.ModifierEngine _engine;

    /// <summary>
    /// Initializes a new instance of the <see cref="StackPreviewConduit"/> class.
    /// </summary>
    /// <param name="engine">The central modifier engine providing stacks to preview.</param>
    public StackPreviewConduit(RhinoModifiers.Runtime.ModifierEngine engine)
    {
        _engine = engine;
    }

    /// <inheritdoc/>
    protected override void CalculateBoundingBox(CalculateBoundingBoxEventArgs e)
    {
        foreach (var stack in _engine.GetPreviewStacks(RhinoDoc.ActiveDoc))
        {
            foreach (var geometry in stack.Geometry)
            {
                e.IncludeBoundingBox(geometry.GetBoundingBox(true));
            }
        }
    }

    /// <inheritdoc/>
    protected override void PreDrawObject(DrawObjectEventArgs e)
    {
        if (_engine.GetManagedObjectIds(e.RhinoObject.Document).Contains(e.RhinoObject.Id))
        {
            e.DrawObject = false;
        }
    }

    /// <inheritdoc/>
    protected override void PostDrawObjects(DrawEventArgs e)
    {
        foreach (var objectId in _engine.GetManagedObjectIds(e.RhinoDoc))
        {
            var sourceObject = e.RhinoDoc.Objects.FindId(objectId);
            var drawColor = GetPreviewColor(e.RhinoDoc, sourceObject);
            DrawSourceWireframe(e.Display, sourceObject, drawColor);
        }

        foreach (var stack in _engine.GetPreviewStacks(e.RhinoDoc))
        {
            var sourceObject = e.RhinoDoc.Objects.FindId(stack.SourceObjectId);
            var drawColor = GetPreviewColor(e.RhinoDoc, sourceObject);
            using var material = CreatePreviewMaterial(sourceObject, drawColor);

            foreach (var geometry in stack.Geometry)
            {
                DrawGeometry(e.Display, geometry, drawColor, material);
            }
        }
    }

    private static Color GetPreviewColor(RhinoDoc doc, RhinoObject? sourceObject)
    {
        return sourceObject?.Attributes.DrawColor(doc) ?? PreviewColor;
    }

    private static DisplayMaterial CreatePreviewMaterial(
        RhinoObject? sourceObject,
        Color fallbackColor
    )
    {
        var sourceMaterial = sourceObject?.GetMaterial(true);
        return sourceMaterial is null
            ? new DisplayMaterial(fallbackColor)
            : new DisplayMaterial(sourceMaterial);
    }

    private static void DrawSourceWireframe(
        DisplayPipeline display,
        RhinoObject? sourceObject,
        Color drawColor
    )
    {
        if (
            sourceObject is null
            || !RhinoModifiers.Runtime.GeometryConversion.TryGetSourceGeometry(
                sourceObject.Geometry,
                out var geometry,
                out _
            )
        )
        {
            return;
        }

        foreach (var item in geometry)
        {
            GeometryRenderer.Draw(display, item, drawColor, RenderStyle.Wireframe);
        }
    }

    private static void DrawGeometry(
        DisplayPipeline display,
        GeometryBase geometry,
        Color drawColor,
        DisplayMaterial material
    )
    {
        GeometryRenderer.Draw(display, geometry, drawColor, RenderStyle.Shaded, material);
    }
}
